sonar.projectKey=adrien-fort_tweo
sonar.organization=adrien-fort

sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.version=3.12

sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.sourceEncoding=UTF-8
