"""initial_schema

Revision ID: 0d7b3fac8079
Revises:
Create Date: 2026-06-03 00:43:28.520013

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d7b3fac8079"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("email_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("system_role", sa.String(length=16), nullable=False),
        sa.Column("gender", sa.String(length=64), nullable=True),
        sa.Column("pronouns", sa.String(length=64), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("preferences", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("firebase_uid"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email_hash"), ["email_hash"], unique=True)

    op.create_table(
        "event_series",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("organiser_id", sa.String(length=36), nullable=False),
        sa.Column("recurrence", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organiser_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event_series", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_series_organiser_id"), ["organiser_id"], unique=False)

    op.create_table(
        "user_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=True),
        sa.Column("series_sequence", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("activity_type", sa.String(length=32), nullable=False),
        sa.Column("organiser_id", sa.String(length=36), nullable=False),
        sa.Column("privacy", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organiser_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["event_series.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_organiser_id"), ["organiser_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_series_id"), ["series_id"], unique=False)

    op.create_table(
        "user_group_memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("added_by", sa.String(length=36), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["user_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_group_memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_group_memberships_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_group_memberships_user_id"), ["user_id"], unique=False)

    op.create_table(
        "event_memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("invited_by", sa.String(length=36), nullable=False),
        sa.Column("invited_via_group_id", sa.String(length=36), nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_via_group_id"],
            ["user_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("event_memberships", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_memberships_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_memberships_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_event_memberships_event_id"))

    op.drop_table("event_memberships")
    with op.batch_alter_table("user_group_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_group_memberships_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_group_memberships_group_id"))

    op.drop_table("user_group_memberships")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_series_id"))
        batch_op.drop_index(batch_op.f("ix_events_organiser_id"))

    op.drop_table("events")
    op.drop_table("user_groups")
    with op.batch_alter_table("event_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_series_organiser_id"))

    op.drop_table("event_series")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email_hash"))

    op.drop_table("users")
    # ### end Alembic commands ###
